### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by explowz** [sirlucjan/aur#4]
This is not really an issue, but a question. Since I'm looking for a kernel that needs to be patched with Project C and UKSMD, are there any cachyOS kernels that offer that, or can I just fork it and manually add the needed Project C patch like I've been doing until now? How does 0001-prjc-cachy.patch differ from what's offered on gitlab.com/alfredchen/projectc, or is it overall the same?

**Comment by ptr1337** [comment]
if you are running this on a server, I dont think that prjc is a good suggestion for.
Actually I would suggest you more cfs, its way more optimized in the usage with more cpu's.

**numa:**
**Numa is a big benefit for you in that points, specially it includes patches also from the next kernel.**

**_mq_deadline_disable and _kyber_disable:**
You dont really need this if you have a hdd or ssd on your server, its actually the disk scheduler and bfq should provide you the best performance

**_use_llvm_lto**:
With that option you can build your kernel with clang and THIN or FULL lto enabled, sometimes it gives you a better performance
But better stick to gcc in your usage

**_use_kcfi**:
This just work if you are using a patched llvm 15
CFI provides you a better security for the kernel but can bring a overhead all in all.
More you can find here:
https://lore.kernel.org/lkml/20220610233513.1798771-1-samitolvanen@google.com/

**_bcachefs**:
This is a addition for a new filesystem which is aimed to get soon to upstream - You wont need this if you are not using it.

Actually I would also suggest you to change the preempt to server.
I think you use the server mainly for common server tasks and not desktop usage, right? Then you should also lower the tickrate to maybe 500 or 300

Right now the options which are set as default are mainly thought for the desktop usage, but the kernel can be also used for the server (i use it myself also for the buildserver from CachyOS)

Feel free to ask if you still have questions.

Regards

**Comment by ptr1337** [comment]
Actually there is a great tool, to just enable the modules which you need which reduces the config a lot:
https://wiki.archlinux.org/title/Modprobed-db

Just be sure that you let it a time running and store the modules, there module needs explicitly called so that it will get into the list.
Just read the wiki clear enough, its easy to understand.

 As long you are sure that you dont need the things, you can safely disable them. 
One thing which can improve your performance is to disable mitigations, which is now possible via the config but in terms of security it is really not suggested. It depends if you are hosting services and you a target of attackers and have ports published, better to stay it disabled. Can be also done via the cmdline option mitigations=off

Here you can find other things which can improve the performance:
https://wiki.archlinux.org/title/Improving_performance

Mainly you should check your fstab option, e.G noatime,nodiratime with HDD's. Also changing the disk scheduler to bfq should help you, if its not already used.
Here you can set a simple option to use this automatically, depending on your drive you has:
```
/etc/udev/rules.d/60-ioschedulers.rules

# set scheduler for NVMe
ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
# set scheduler for SSD and eMMC
ACTION=="add|change", KERNEL=="sd[a-z]*|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"
# set scheduler for rotating disks
ACTION=="add|change", KERNEL=="sd[a-z]*", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
```

BMQ/PDS is mainly thought for desktop usage and gaming. Stay with cfs and enable NUMA, it will probably improve your performance.

**Comment by sirlucjan** [comment]
BMQ and PDS under the server are not suitable at all. CFS or BORE and nothing else.

**Comment by ptr1337** [comment]
> @ptr1337 You said that you'd recommend CFS, since BMQ/PDS is more for gaming, but the server is used for hosting game servers. Would CFS still be a good option then?

Yes, it is. Actually nearly no custom scheduler has a good NUMA support it, which is mainly needed for your setup.
Actually you will have a WAY better Multicore performance.

Are you hosting game servers on it? I just heard that maybe a higher tickrate to 500 Hz could help, 1000 Hz is way to much if you hosting things. Its really not needed.

**Comment by ptr1337** [comment]
Yes, stay with that. And even for that it is not good to run pds/bmq. Its really shit with your usage.

**Comment by ptr1337** [comment]
What do you mean with "correctly" ?
There are several default sysctl options you "tune", there are several guides out there.

Do you face into issues ?

**Comment by ptr1337** [comment]
> I don't think so? It seems to work fine. I was just asking if there's any kernel options that need to be messed with in order to allow the kernel to be at its best. For BMQ I was told to always use kernel.yield_type=2. Online I see articles saying that for CFS kernel.sched_min_granularity_ns, kernel.sched_latency_ns and kernel.sched_wakeup_granularity_ns need to be tuned in order to achieve greater performance.

Some of these are already tweaked in the "0001-cachy.patch" which is applied to the kernel you use.
